import { ModelPricingConfig, PricingUnit } from '../pricing-data';

export const OPENAI_PRICING: ModelPricingConfig[] = [
  // === GPT-5 Models (Latest) ===
  {
    modelId: 'gpt-5',
    modelName: 'GPT-5',
    provider: 'OpenAI',
    inputPrice: 1.25,
    outputPrice: 10.0,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'reasoning', 'analysis', 'advanced-intelligence'],
    category: 'text',
    isLatest: true,
    notes: 'Latest GPT-5 model with advanced intelligence and reasoning capabilities'
  },
  {
    modelId: 'gpt-5-mini',
    modelName: 'GPT-5 Mini',
    provider: 'OpenAI',
    inputPrice: 0.25,
    outputPrice: 2.0,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'reasoning', 'analysis', 'efficient'],
    category: 'text',
    isLatest: true,
    notes: 'Efficient GPT-5 variant with balanced performance and cost'
  },
  {
    modelId: 'gpt-5-nano',
    modelName: 'GPT-5 nano',
    provider: 'OpenAI',
    inputPrice: 0.05,
    outputPrice: 0.4,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'fast', 'cost-effective'],
    category: 'text',
    isLatest: true,
    notes: 'Fastest, most cost-efficient version of GPT-5'
  },
  {
    modelId: 'gpt-5-pro',
    modelName: 'GPT-5 pro',
    provider: 'OpenAI',
    inputPrice: 15.0,
    outputPrice: 120.0,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'reasoning', 'analysis', 'coding', 'agents', 'premium'],
    category: 'text',
    isLatest: true,
    notes: 'Version of GPT-5 that produces smarter and more precise responses. Batch: $7.50/$60.00'
  },
  {
    modelId: 'gpt-5-codex',
    modelName: 'GPT-5-Codex',
    provider: 'OpenAI',
    inputPrice: 1.25,
    outputPrice: 10.0,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['code', 'programming', 'agents', 'coding'],
    category: 'code',
    isLatest: true,
    notes: 'A version of GPT-5 optimized for agentic coding in Codex'
  },
  {
    modelId: 'gpt-5-chat-latest',
    modelName: 'GPT-5 Chat',
    provider: 'OpenAI',
    inputPrice: 1.25,
    outputPrice: 10.0,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'chat', 'reasoning', 'analysis'],
    category: 'text',
    isLatest: true,
    notes: 'GPT-5 model used in ChatGPT (not recommended for API use)'
  },

  // === GPT-4.1 Series (Latest) ===
  {
    modelId: 'gpt-4.1',
    modelName: 'GPT-4.1',
    provider: 'OpenAI',
    inputPrice: 2.0,
    outputPrice: 8.0,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'analysis', 'enhanced'],
    category: 'text',
    isLatest: true,
    notes: 'Smartest non-reasoning model'
  },
  {
    modelId: 'gpt-4.1-mini',
    modelName: 'GPT-4.1 mini',
    provider: 'OpenAI',
    inputPrice: 0.4,
    outputPrice: 1.6,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'analysis', 'efficient'],
    category: 'text',
    isLatest: true,
    notes: 'Smaller, faster version of GPT-4.1'
  },
  {
    modelId: 'gpt-4.1-nano',
    modelName: 'GPT-4.1 nano',
    provider: 'OpenAI',
    inputPrice: 0.1,
    outputPrice: 0.4,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'fast', 'cost-effective'],
    category: 'text',
    isLatest: true,
    notes: 'Fastest, most cost-efficient version of GPT-4.1'
  },

  // === GPT-4o Series (Latest) ===
  {
    modelId: 'gpt-4o-2024-08-06',
    modelName: 'GPT-4o',
    provider: 'OpenAI',
    inputPrice: 5.0,
    outputPrice: 15.0,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'vision', 'multimodal', 'analysis'],
    category: 'multimodal',
    isLatest: true,
    notes: 'Fast, intelligent, flexible GPT model. Cached: $0.50. Batch: $2.50/$7.50'
  },
  {
    modelId: 'gpt-4o-2024-05-13',
    modelName: 'GPT-4o (2024-05-13)',
    provider: 'OpenAI',
    inputPrice: 5.0,
    outputPrice: 15.0,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'vision', 'multimodal'],
    category: 'multimodal',
    isLatest: false,
    notes: 'GPT-4o model from May 2024'
  },
  {
    modelId: 'gpt-4o-audio-preview',
    modelName: 'GPT-4o Audio Preview',
    provider: 'OpenAI',
    inputPrice: 2.5,
    outputPrice: 10.0,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'audio', 'multimodal'],
    category: 'audio',
    isLatest: true,
    notes: 'GPT-4o with audio input capabilities'
  },
  {
    modelId: 'gpt-4o-realtime-preview',
    modelName: 'GPT-4o Realtime Preview',
    provider: 'OpenAI',
    inputPrice: 4.0,
    outputPrice: 16.0,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'realtime', 'multimodal'],
    category: 'realtime',
    isLatest: true,
    notes: 'GPT-4o with realtime processing capabilities. Cached: $0.40. Audio: $32/$64 per 1M'
  },
  {
    modelId: 'gpt-4o-mini-2024-07-18',
    modelName: 'GPT-4o Mini',
    provider: 'OpenAI',
    inputPrice: 0.15,
    outputPrice: 0.6,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'vision', 'multimodal', 'efficient'],
    category: 'multimodal',
    isLatest: true,
    notes: 'Efficient GPT-4o variant with multimodal capabilities'
  },
  {
    modelId: 'gpt-4o-mini-audio-preview',
    modelName: 'GPT-4o Mini Audio Preview',
    provider: 'OpenAI',
    inputPrice: 0.15,
    outputPrice: 0.6,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'audio', 'efficient'],
    category: 'audio',
    isLatest: true,
    notes: 'GPT-4o Mini with audio input capabilities'
  },
  {
    modelId: 'gpt-4o-mini-realtime-preview',
    modelName: 'GPT-4o Mini Realtime Preview',
    provider: 'OpenAI',
    inputPrice: 0.6,
    outputPrice: 2.4,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'realtime', 'efficient'],
    category: 'realtime',
    isLatest: true,
    notes: 'GPT-4o Mini with realtime processing capabilities'
  },

  // === O-Series Models (Latest) ===
  {
    modelId: 'o3-pro',
    modelName: 'o3-pro',
    provider: 'OpenAI',
    inputPrice: 20.0,
    outputPrice: 80.0,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'reasoning', 'analysis', 'pro'],
    category: 'reasoning',
    isLatest: true,
    notes: 'Version of o3 with more compute for better responses'
  },
  {
    modelId: 'o3-deep-research',
    modelName: 'o3-deep-research',
    provider: 'OpenAI',
    inputPrice: 10.0,
    outputPrice: 40.0,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'research', 'analysis', 'deep'],
    category: 'research',
    isLatest: true,
    notes: 'Our most powerful deep research model'
  },
  {
    modelId: 'o4-mini',
    modelName: 'o4-mini',
    provider: 'OpenAI',
    inputPrice: 1.1,
    outputPrice: 4.4,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'reasoning', 'efficient'],
    category: 'reasoning',
    isLatest: true,
    notes: 'Fast, cost-efficient reasoning model, succeeded by GPT-5 mini'
  },
  {
    modelId: 'o4-mini-deep-research',
    modelName: 'o4-mini-deep-research',
    provider: 'OpenAI',
    inputPrice: 2.0,
    outputPrice: 8.0,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'research', 'analysis', 'efficient'],
    category: 'research',
    isLatest: true,
    notes: 'Faster, more affordable deep research model'
  },
  {
    modelId: 'o3',
    modelName: 'o3',
    provider: 'OpenAI',
    inputPrice: 2.0,
    outputPrice: 8.0,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'reasoning', 'analysis'],
    category: 'reasoning',
    isLatest: true,
    notes: 'Reasoning model for complex tasks, succeeded by GPT-5'
  },
  {
    modelId: 'o1-pro',
    modelName: 'o1-pro',
    provider: 'OpenAI',
    inputPrice: 150.0,
    outputPrice: 600.0,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'reasoning', 'analysis', 'premium'],
    category: 'reasoning',
    isLatest: true,
    notes: 'Version of o1 with more compute for better responses'
  },
  {
    modelId: 'o1',
    modelName: 'o1',
    provider: 'OpenAI',
    inputPrice: 15.0,
    outputPrice: 60.0,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'reasoning', 'analysis', 'advanced'],
    category: 'reasoning',
    isLatest: false,
    notes: 'Previous full o-series reasoning model'
  },
  {
    modelId: 'o3-mini',
    modelName: 'o3-mini',
    provider: 'OpenAI',
    inputPrice: 1.1,
    outputPrice: 4.4,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'reasoning', 'efficient'],
    category: 'reasoning',
    isLatest: false,
    notes: 'A small model alternative to o3'
  },
  {
    modelId: 'o1-mini',
    modelName: 'o1-mini',
    provider: 'OpenAI',
    inputPrice: 1.1,
    outputPrice: 4.4,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'reasoning', 'efficient'],
    category: 'reasoning',
    isLatest: false,
    notes: 'Deprecated - A small model alternative to o1'
  },

  // === Video Generation Models ===
  {
    modelId: 'sora-2',
    modelName: 'Sora 2',
    provider: 'OpenAI',
    inputPrice: 0.1,
    outputPrice: 0.1,
    unit: PricingUnit.PerSecond,
    contextWindow: 0,
    capabilities: ['video-generation', 'audio', 'synced-audio'],
    category: 'video',
    isLatest: true,
    notes: 'Flagship video generation with synced audio. $0.10/sec (720p)'
  },
  {
    modelId: 'sora-2-pro',
    modelName: 'Sora 2 Pro',
    provider: 'OpenAI',
    inputPrice: 0.3,
    outputPrice: 0.3,
    unit: PricingUnit.PerSecond,
    contextWindow: 0,
    capabilities: ['video-generation', 'audio', 'synced-audio', 'advanced'],
    category: 'video',
    isLatest: true,
    notes: 'Most advanced synced-audio video generation. $0.30/sec (720p), $0.50/sec (1024p)'
  },

  // === Image Generation Models ===
  {
    modelId: 'gpt-image-1',
    modelName: 'GPT Image 1',
    provider: 'OpenAI',
    inputPrice: 5.0,
    outputPrice: 0.0,
    unit: PricingUnit.PerRequest,
    contextWindow: 0,
    capabilities: ['image-generation', 'text-to-image'],
    category: 'image',
    isLatest: true,
    notes:
      'State-of-the-art image generation model. Cached: $1.25. Low: $0.011, Med: $0.042, High: $0.167/img'
  },
  {
    modelId: 'gpt-image-1-mini',
    modelName: 'gpt-image-1-mini',
    provider: 'OpenAI',
    inputPrice: 2.0,
    outputPrice: 0.0,
    unit: PricingUnit.PerRequest,
    contextWindow: 0,
    capabilities: ['image-generation', 'text-to-image', 'cost-efficient'],
    category: 'image',
    isLatest: true,
    notes:
      'A cost-efficient version of GPT Image 1. Cached: $0.20. Low: $0.005, Med: $0.011, High: $0.036/img'
  },
  {
    modelId: 'dall-e-3',
    modelName: 'DALL·E 3',
    provider: 'OpenAI',
    inputPrice: 0.04,
    outputPrice: 0.04,
    unit: PricingUnit.PerRequest,
    contextWindow: 0,
    capabilities: ['image-generation', 'text-to-image'],
    category: 'image',
    isLatest: false,
    notes: 'Previous generation image generation model'
  },
  {
    modelId: 'dall-e-2',
    modelName: 'DALL·E 2',
    provider: 'OpenAI',
    inputPrice: 0.02,
    outputPrice: 0.02,
    unit: PricingUnit.PerRequest,
    contextWindow: 0,
    capabilities: ['image-generation', 'text-to-image'],
    category: 'image',
    isLatest: false,
    notes: 'Our first image generation model'
  },

  // === Audio and Realtime Models ===
  {
    modelId: 'gpt-realtime',
    modelName: 'gpt-realtime',
    provider: 'OpenAI',
    inputPrice: 4.0,
    outputPrice: 16.0,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'audio', 'realtime', 'multimodal'],
    category: 'realtime',
    isLatest: true,
    notes:
      'Model capable of realtime text and audio inputs and outputs. Cached: $0.40. Audio: $32/$64 per 1M'
  },
  {
    modelId: 'gpt-realtime-mini',
    modelName: 'gpt-realtime-mini',
    provider: 'OpenAI',
    inputPrice: 0.6,
    outputPrice: 2.4,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'audio', 'realtime', 'efficient'],
    category: 'realtime',
    isLatest: true,
    notes: 'A cost-efficient version of GPT Realtime. Cached: $0.06. Audio: $10/$20 per 1M'
  },
  {
    modelId: 'gpt-audio',
    modelName: 'gpt-audio',
    provider: 'OpenAI',
    inputPrice: 2.5,
    outputPrice: 10.0,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'audio', 'multimodal'],
    category: 'audio',
    isLatest: true,
    notes: 'For audio inputs and outputs with Chat Completions API'
  },
  {
    modelId: 'gpt-audio-mini',
    modelName: 'gpt-audio-mini',
    provider: 'OpenAI',
    inputPrice: 0.6,
    outputPrice: 2.4,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'audio', 'efficient'],
    category: 'audio',
    isLatest: true,
    notes: 'A cost-efficient version of GPT Audio. Audio: $10/$20 per 1M'
  },

  // === Transcription Models ===
  {
    modelId: 'gpt-4o-transcribe',
    modelName: 'GPT-4o Transcribe',
    provider: 'OpenAI',
    inputPrice: 2.5,
    outputPrice: 10.0,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 0,
    capabilities: ['audio', 'transcription', 'speech-to-text'],
    category: 'audio',
    isLatest: true,
    notes: 'Speech-to-text model powered by GPT-4o. ~$0.006/min'
  },
  {
    modelId: 'gpt-4o-transcribe-diarize',
    modelName: 'GPT-4o Transcribe Diarize',
    provider: 'OpenAI',
    inputPrice: 0.2,
    outputPrice: 0.2,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 0,
    capabilities: ['audio', 'transcription', 'speech-to-text', 'diarization'],
    category: 'audio',
    isLatest: true,
    notes: "Transcription model that identifies who's speaking when"
  },
  {
    modelId: 'gpt-4o-mini-transcribe',
    modelName: 'GPT-4o mini Transcribe',
    provider: 'OpenAI',
    inputPrice: 1.25,
    outputPrice: 5.0,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 0,
    capabilities: ['audio', 'transcription', 'speech-to-text', 'efficient'],
    category: 'audio',
    isLatest: true,
    notes: 'Speech-to-text model powered by GPT-4o mini. ~$0.003/min'
  },
  {
    modelId: 'whisper-1',
    modelName: 'Whisper',
    provider: 'OpenAI',
    inputPrice: 0.006,
    outputPrice: 0.006,
    unit: PricingUnit.PerMinute,
    contextWindow: 0,
    capabilities: ['audio', 'transcription', 'speech-to-text', 'general-purpose'],
    category: 'audio',
    isLatest: true,
    notes: 'General-purpose speech recognition model'
  },

  // === Text-to-Speech Models ===
  {
    modelId: 'gpt-4o-mini-tts',
    modelName: 'GPT-4o mini TTS',
    provider: 'OpenAI',
    inputPrice: 0.6,
    outputPrice: 0.0,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 0,
    capabilities: ['audio', 'text-to-speech', 'tts'],
    category: 'audio',
    isLatest: true,
    notes: 'Text-to-speech model powered by GPT-4o mini. ~$0.015/min'
  },
  {
    modelId: 'tts-1',
    modelName: 'TTS-1',
    provider: 'OpenAI',
    inputPrice: 0.015,
    outputPrice: 0.015,
    unit: PricingUnit.Per1KCharacters,
    contextWindow: 0,
    capabilities: ['audio', 'text-to-speech', 'tts', 'fast'],
    category: 'audio',
    isLatest: true,
    notes: 'Text-to-speech model optimized for speed'
  },
  {
    modelId: 'tts-1-hd',
    modelName: 'TTS-1 HD',
    provider: 'OpenAI',
    inputPrice: 0.03,
    outputPrice: 0.03,
    unit: PricingUnit.Per1KCharacters,
    contextWindow: 0,
    capabilities: ['audio', 'text-to-speech', 'tts', 'high-quality'],
    category: 'audio',
    isLatest: true,
    notes: 'Text-to-speech model optimized for quality'
  },

  // === Open-Weight Models ===
  {
    modelId: 'gpt-oss-120b',
    modelName: 'gpt-oss-120b',
    provider: 'OpenAI',
    inputPrice: 2.0,
    outputPrice: 8.0,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 131072,
    capabilities: ['text', 'open-source', 'open-weight'],
    category: 'text',
    isLatest: true,
    notes: 'Most powerful open-weight model, fits into an H100 GPU. Licensed under Apache 2.0'
  },
  {
    modelId: 'gpt-oss-20b',
    modelName: 'gpt-oss-20b',
    provider: 'OpenAI',
    inputPrice: 0.5,
    outputPrice: 2.0,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 131072,
    capabilities: ['text', 'open-source', 'open-weight', 'low-latency'],
    category: 'text',
    isLatest: true,
    notes: 'Medium-sized open-weight model for low latency. Licensed under Apache 2.0'
  },

  // === Specialized Models ===
  {
    modelId: 'codex-mini-latest',
    modelName: 'codex-mini-latest',
    provider: 'OpenAI',
    inputPrice: 1.5,
    outputPrice: 6.0,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['code', 'programming', 'reasoning'],
    category: 'code',
    isLatest: true,
    notes: 'Fast reasoning model optimized for the Codex CLI'
  },
  {
    modelId: 'omni-moderation-latest',
    modelName: 'omni-moderation',
    provider: 'OpenAI',
    inputPrice: 0.1,
    outputPrice: 0.1,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 32768,
    capabilities: ['moderation', 'text', 'image', 'harmful-content-detection'],
    category: 'moderation',
    isLatest: true,
    notes: 'Identify potentially harmful content in text and images'
  },
  {
    modelId: 'gpt-4o-mini-search-preview-2025-03-11',
    modelName: 'GPT-4o Mini Search Preview',
    provider: 'OpenAI',
    inputPrice: 0.15,
    outputPrice: 0.6,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'search', 'multimodal'],
    category: 'search',
    isLatest: true,
    notes: 'Fast, affordable small model for web search'
  },
  {
    modelId: 'gpt-4o-search-preview-2025-03-11',
    modelName: 'GPT-4o Search Preview',
    provider: 'OpenAI',
    inputPrice: 2.5,
    outputPrice: 10.0,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'search', 'multimodal'],
    category: 'search',
    isLatest: true,
    notes: 'GPT model for web search in Chat Completions'
  },
  {
    modelId: 'computer-use-preview-2025-03-11',
    modelName: 'computer-use-preview',
    provider: 'OpenAI',
    inputPrice: 3.0,
    outputPrice: 12.0,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'computer-use', 'automation'],
    category: 'computer-use',
    isLatest: true,
    notes: 'Specialized model for computer use tool. Batch: $1.50/$6.00'
  },

  // === Embedding Models ===
  {
    modelId: 'text-embedding-3-small',
    modelName: 'Text Embedding 3 Small',
    provider: 'OpenAI',
    inputPrice: 0.02,
    outputPrice: 0.02,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 8191,
    capabilities: ['embedding', 'semantic-search'],
    category: 'embedding',
    isLatest: true,
    notes: 'Latest small embedding model for semantic search and analysis'
  },
  {
    modelId: 'text-embedding-3-large',
    modelName: 'Text Embedding 3 Large',
    provider: 'OpenAI',
    inputPrice: 0.13,
    outputPrice: 0.13,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 8191,
    capabilities: ['embedding', 'semantic-search', 'high-quality'],
    category: 'embedding',
    isLatest: true,
    notes: 'Latest large embedding model with highest quality for semantic search'
  },
  {
    modelId: 'text-embedding-ada-002',
    modelName: 'Text Embedding Ada 002',
    provider: 'OpenAI',
    inputPrice: 0.1,
    outputPrice: 0.1,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 8191,
    capabilities: ['embedding', 'semantic-search'],
    category: 'embedding',
    isLatest: false,
    notes: 'Previous generation embedding model for semantic search'
  },

  // === ChatGPT Models ===
  {
    modelId: 'chatgpt-4o-latest',
    modelName: 'ChatGPT-4o',
    provider: 'OpenAI',
    inputPrice: 5.0,
    outputPrice: 15.0,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'vision', 'multimodal', 'chat'],
    category: 'multimodal',
    isLatest: false,
    notes: 'GPT-4o model used in ChatGPT (not recommended for API use)'
  },

  // === Legacy and Deprecated Models ===
  {
    modelId: 'gpt-4.5-preview',
    modelName: 'GPT-4.5 Preview',
    provider: 'OpenAI',
    inputPrice: 10.0,
    outputPrice: 30.0,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'vision', 'multimodal'],
    category: 'multimodal',
    isLatest: false,
    notes: 'Deprecated - Large model'
  },
  {
    modelId: 'o1-preview',
    modelName: 'o1 Preview',
    provider: 'OpenAI',
    inputPrice: 15.0,
    outputPrice: 60.0,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'reasoning', 'analysis'],
    category: 'reasoning',
    isLatest: false,
    notes: 'Deprecated - Preview of our first o-series reasoning model'
  },
  {
    modelId: 'text-moderation-latest',
    modelName: 'text-moderation',
    provider: 'OpenAI',
    inputPrice: 0.1,
    outputPrice: 0.1,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 32768,
    capabilities: ['moderation', 'text', 'harmful-content-detection'],
    category: 'moderation',
    isLatest: false,
    notes: 'Deprecated - Previous generation text-only moderation model'
  },
  {
    modelId: 'text-moderation-stable',
    modelName: 'text-moderation-stable',
    provider: 'OpenAI',
    inputPrice: 0.1,
    outputPrice: 0.1,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 32768,
    capabilities: ['moderation', 'text', 'harmful-content-detection'],
    category: 'moderation',
    isLatest: false,
    notes: 'Deprecated - Previous generation text-only moderation model'
  },
  {
    modelId: 'babbage-002',
    modelName: 'babbage-002',
    provider: 'OpenAI',
    inputPrice: 0.4,
    outputPrice: 0.4,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 16384,
    capabilities: ['text'],
    category: 'text',
    isLatest: false,
    notes: 'Deprecated - Replacement for the GPT-3 ada and babbage base models. Batch: $0.20/$0.20'
  },
  {
    modelId: 'davinci-002',
    modelName: 'davinci-002',
    provider: 'OpenAI',
    inputPrice: 2.0,
    outputPrice: 2.0,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 16384,
    capabilities: ['text'],
    category: 'text',
    isLatest: false,
    notes:
      'Deprecated - Replacement for the GPT-3 curie and davinci base models. Batch: $1.00/$1.00'
  },
  {
    modelId: 'gpt-4o-mini',
    modelName: 'GPT-4o mini',
    provider: 'OpenAI',
    inputPrice: 0.15,
    outputPrice: 0.6,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'vision', 'multimodal'],
    category: 'multimodal',
    isLatest: false,
    notes: 'Fast, affordable small model for focused tasks'
  },
  {
    modelId: 'gpt-4o',
    modelName: 'GPT-4o',
    provider: 'OpenAI',
    inputPrice: 2.5,
    outputPrice: 10.0,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'vision', 'multimodal'],
    category: 'multimodal',
    isLatest: false,
    notes: 'Fast, intelligent, flexible GPT model'
  },
  {
    modelId: 'gpt-4-turbo',
    modelName: 'GPT-4 Turbo',
    provider: 'OpenAI',
    inputPrice: 10.0,
    outputPrice: 30.0,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'vision', 'multimodal'],
    category: 'multimodal',
    isLatest: false,
    notes: 'Legacy GPT-4 Turbo model'
  },
  {
    modelId: 'gpt-4',
    modelName: 'GPT-4',
    provider: 'OpenAI',
    inputPrice: 30.0,
    outputPrice: 60.0,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 8192,
    capabilities: ['text'],
    category: 'text',
    isLatest: false,
    notes: 'Legacy GPT-4 base model'
  },
  {
    modelId: 'gpt-3.5-turbo-0125',
    modelName: 'GPT-3.5 Turbo (0125)',
    provider: 'OpenAI',
    inputPrice: 0.5,
    outputPrice: 1.5,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 16385,
    capabilities: ['text'],
    category: 'text',
    isLatest: false,
    notes: 'Legacy GPT-3.5 Turbo model'
  },
  {
    modelId: 'gpt-3.5-turbo',
    modelName: 'GPT-3.5 Turbo',
    provider: 'OpenAI',
    inputPrice: 0.5,
    outputPrice: 1.5,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 16385,
    capabilities: ['text'],
    category: 'text',
    isLatest: false,
    notes: 'Legacy GPT-3.5 Turbo model'
  }
];
