import { ModelPricingConfig, PricingUnit } from '../pricing-data';

export const OPENAI_PRICING: ModelPricingConfig[] = [
  // === GPT-5 Models (Latest) ===
  {
    modelId: 'gpt-5',
    modelName: 'GPT-5',
    provider: 'OpenAI',
    inputPrice: 1.25,
    outputPrice: 10.00,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'reasoning', 'analysis', 'advanced-intelligence'],
    category: 'text',
    isLatest: true,
    notes: 'Latest GPT-5 model with advanced intelligence and reasoning capabilities'
  },
  {
    modelId: 'gpt-5-mini',
    modelName: 'GPT-5 Mini',
    provider: 'OpenAI',
    inputPrice: 0.25,
    outputPrice: 2.00,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'reasoning', 'analysis', 'efficient'],
    category: 'text',
    isLatest: true,
    notes: 'Efficient GPT-5 variant with balanced performance and cost'
  },
  {
    modelId: 'gpt-5-nano',
    modelName: 'GPT-5 Nano',
    provider: 'OpenAI',
    inputPrice: 0.05,
    outputPrice: 0.40,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'fast', 'cost-effective'],
    category: 'text',
    isLatest: true,
    notes: 'Fastest and most cost-effective GPT-5 variant'
  },
  {
    modelId: 'gpt-5-chat-latest',
    modelName: 'GPT-5 Chat Latest',
    provider: 'OpenAI',
    inputPrice: 1.25,
    outputPrice: 10.00,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'chat', 'reasoning', 'analysis'],
    category: 'text',
    isLatest: true,
    notes: 'Latest GPT-5 chat model with advanced conversational capabilities'
  },

  // === GPT-4.1 Series (Latest) ===
  {
    modelId: 'gpt-4.1-2025-04-14',
    modelName: 'GPT-4.1',
    provider: 'OpenAI',
    inputPrice: 2.00,
    outputPrice: 8.00,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'analysis', 'reasoning', 'enhanced'],
    category: 'text',
    isLatest: true,
    notes: 'Latest GPT-4.1 model with enhanced capabilities and reasoning'
  },
  {
    modelId: 'gpt-4.1-mini-2025-04-14',
    modelName: 'GPT-4.1 Mini',
    provider: 'OpenAI',
    inputPrice: 0.40,
    outputPrice: 1.60,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'analysis', 'efficient'],
    category: 'text',
    isLatest: true,
    notes: 'Efficient GPT-4.1 variant with balanced performance'
  },
  {
    modelId: 'gpt-4.1-nano-2025-04-14',
    modelName: 'GPT-4.1 Nano',
    provider: 'OpenAI',
    inputPrice: 0.10,
    outputPrice: 0.40,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'fast', 'cost-effective'],
    category: 'text',
    isLatest: true,
    notes: 'Fastest and most cost-effective GPT-4.1 variant'
  },

  // === GPT-4o Series (Latest) ===
  {
    modelId: 'gpt-4o-2024-08-06',
    modelName: 'GPT-4o',
    provider: 'OpenAI',
    inputPrice: 2.50,
    outputPrice: 10.00,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'vision', 'multimodal', 'analysis'],
    category: 'multimodal',
    isLatest: true,
    notes: 'Latest GPT-4o model with multimodal capabilities'
  },
  {
    modelId: 'gpt-4o-2024-05-13',
    modelName: 'GPT-4o (2024-05-13)',
    provider: 'OpenAI',
    inputPrice: 5.00,
    outputPrice: 15.00,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'vision', 'multimodal'],
    category: 'multimodal',
    isLatest: false,
    notes: 'GPT-4o model from May 2024'
  },
  {
    modelId: 'gpt-4o-audio-preview',
    modelName: 'GPT-4o Audio Preview',
    provider: 'OpenAI',
    inputPrice: 2.50,
    outputPrice: 10.00,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'audio', 'multimodal'],
    category: 'audio',
    isLatest: true,
    notes: 'GPT-4o with audio input capabilities'
  },
  {
    modelId: 'gpt-4o-realtime-preview',
    modelName: 'GPT-4o Realtime Preview',
    provider: 'OpenAI',
    inputPrice: 5.00,
    outputPrice: 20.00,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'realtime', 'multimodal'],
    category: 'realtime',
    isLatest: true,
    notes: 'GPT-4o with realtime processing capabilities'
  },
  {
    modelId: 'gpt-4o-mini-2024-07-18',
    modelName: 'GPT-4o Mini',
    provider: 'OpenAI',
    inputPrice: 0.15,
    outputPrice: 0.60,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'vision', 'multimodal', 'efficient'],
    category: 'multimodal',
    isLatest: true,
    notes: 'Efficient GPT-4o variant with multimodal capabilities'
  },
  {
    modelId: 'gpt-4o-mini-audio-preview',
    modelName: 'GPT-4o Mini Audio Preview',
    provider: 'OpenAI',
    inputPrice: 0.15,
    outputPrice: 0.60,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'audio', 'efficient'],
    category: 'audio',
    isLatest: true,
    notes: 'GPT-4o Mini with audio input capabilities'
  },
  {
    modelId: 'gpt-4o-mini-realtime-preview',
    modelName: 'GPT-4o Mini Realtime Preview',
    provider: 'OpenAI',
    inputPrice: 0.60,
    outputPrice: 2.40,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'realtime', 'efficient'],
    category: 'realtime',
    isLatest: true,
    notes: 'GPT-4o Mini with realtime processing capabilities'
  },

  // === O-Series Models (Latest) ===
  {
    modelId: 'o1-2024-12-17',
    modelName: 'O1',
    provider: 'OpenAI',
    inputPrice: 15.00,
    outputPrice: 60.00,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'reasoning', 'analysis', 'advanced'],
    category: 'reasoning',
    isLatest: true,
    notes: 'Advanced reasoning model with enhanced capabilities'
  },
  {
    modelId: 'o1-pro-2025-03-19',
    modelName: 'O1 Pro',
    provider: 'OpenAI',
    inputPrice: 150.00,
    outputPrice: 600.00,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'reasoning', 'analysis', 'premium'],
    category: 'reasoning',
    isLatest: true,
    notes: 'Premium reasoning model with highest capabilities'
  },
  {
    modelId: 'o3-pro-2025-06-10',
    modelName: 'O3 Pro',
    provider: 'OpenAI',
    inputPrice: 20.00,
    outputPrice: 80.00,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'reasoning', 'analysis', 'pro'],
    category: 'reasoning',
    isLatest: true,
    notes: 'Professional reasoning model with advanced capabilities'
  },
  {
    modelId: 'o3-2025-04-16',
    modelName: 'O3',
    provider: 'OpenAI',
    inputPrice: 2.00,
    outputPrice: 8.00,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'reasoning', 'analysis'],
    category: 'reasoning',
    isLatest: true,
    notes: 'Standard reasoning model with balanced capabilities'
  },
  {
    modelId: 'o3-deep-research-2025-06-26',
    modelName: 'O3 Deep Research',
    provider: 'OpenAI',
    inputPrice: 10.00,
    outputPrice: 40.00,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'research', 'analysis', 'deep'],
    category: 'research',
    isLatest: true,
    notes: 'Deep research model optimized for complex analysis'
  },
  {
    modelId: 'o4-mini-2025-04-16',
    modelName: 'O4 Mini',
    provider: 'OpenAI',
    inputPrice: 1.10,
    outputPrice: 4.40,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'reasoning', 'efficient'],
    category: 'reasoning',
    isLatest: true,
    notes: 'Efficient O4 variant with balanced performance'
  },
  {
    modelId: 'o4-mini-deep-research-2025-06-26',
    modelName: 'O4 Mini Deep Research',
    provider: 'OpenAI',
    inputPrice: 2.00,
    outputPrice: 8.00,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'research', 'analysis', 'efficient'],
    category: 'research',
    isLatest: true,
    notes: 'Efficient deep research model for cost-sensitive applications'
  },
  {
    modelId: 'o3-mini-2025-01-31',
    modelName: 'O3 Mini',
    provider: 'OpenAI',
    inputPrice: 1.10,
    outputPrice: 4.40,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'reasoning', 'efficient'],
    category: 'reasoning',
    isLatest: false,
    notes: 'Efficient O3 variant with balanced performance'
  },
  {
    modelId: 'o1-mini-2024-09-12',
    modelName: 'O1 Mini',
    provider: 'OpenAI',
    inputPrice: 1.10,
    outputPrice: 4.40,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'reasoning', 'efficient'],
    category: 'reasoning',
    isLatest: false,
    notes: 'Efficient O1 variant with balanced performance'
  },

  // === Specialized Models ===
  {
    modelId: 'codex-mini-latest',
    modelName: 'Codex Mini Latest',
    provider: 'OpenAI',
    inputPrice: 1.50,
    outputPrice: 6.00,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['code', 'programming', 'analysis'],
    category: 'code',
    isLatest: true,
    notes: 'Latest Codex model optimized for code generation and analysis'
  },
  {
    modelId: 'gpt-4o-mini-search-preview-2025-03-11',
    modelName: 'GPT-4o Mini Search Preview',
    provider: 'OpenAI',
    inputPrice: 0.15,
    outputPrice: 0.60,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'search', 'multimodal'],
    category: 'search',
    isLatest: true,
    notes: 'GPT-4o Mini with search capabilities for enhanced information retrieval'
  },
  {
    modelId: 'gpt-4o-search-preview-2025-03-11',
    modelName: 'GPT-4o Search Preview',
    provider: 'OpenAI',
    inputPrice: 2.50,
    outputPrice: 10.00,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'search', 'multimodal'],
    category: 'search',
    isLatest: true,
    notes: 'GPT-4o with search capabilities for enhanced information retrieval'
  },
  {
    modelId: 'computer-use-preview-2025-03-11',
    modelName: 'Computer Use Preview',
    provider: 'OpenAI',
    inputPrice: 3.00,
    outputPrice: 12.00,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'computer-use', 'automation'],
    category: 'computer-use',
    isLatest: true,
    notes: 'Model optimized for computer use and automation tasks'
  },

  // === Embedding Models ===
  {
    modelId: 'text-embedding-3-small',
    modelName: 'Text Embedding 3 Small',
    provider: 'OpenAI',
    inputPrice: 0.02,
    outputPrice: 0.02,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 8191,
    capabilities: ['embedding', 'semantic-search'],
    category: 'embedding',
    isLatest: true,
    notes: 'Latest small embedding model for semantic search and analysis'
  },
  {
    modelId: 'text-embedding-3-large',
    modelName: 'Text Embedding 3 Large',
    provider: 'OpenAI',
    inputPrice: 0.13,
    outputPrice: 0.13,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 8191,
    capabilities: ['embedding', 'semantic-search', 'high-quality'],
    category: 'embedding',
    isLatest: true,
    notes: 'Latest large embedding model with highest quality for semantic search'
  },
  {
    modelId: 'text-embedding-ada-002',
    modelName: 'Text Embedding Ada 002',
    provider: 'OpenAI',
    inputPrice: 0.10,
    outputPrice: 0.10,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 8191,
    capabilities: ['embedding', 'semantic-search'],
    category: 'embedding',
    isLatest: false,
    notes: 'Previous generation embedding model for semantic search'
  },

  // === Legacy Models ===
  {
    modelId: 'gpt-4o-mini',
    modelName: 'GPT-4o Mini (Legacy)',
    provider: 'OpenAI',
    inputPrice: 0.15,
    outputPrice: 0.60,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'vision', 'multimodal'],
    category: 'multimodal',
    isLatest: false,
    notes: 'Legacy GPT-4o Mini model'
  },
  {
    modelId: 'gpt-4o',
    modelName: 'GPT-4o (Legacy)',
    provider: 'OpenAI',
    inputPrice: 2.50,
    outputPrice: 10.00,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'vision', 'multimodal'],
    category: 'multimodal',
    isLatest: false,
    notes: 'Legacy GPT-4o model'
  },
  {
    modelId: 'gpt-4-turbo',
    modelName: 'GPT-4 Turbo',
    provider: 'OpenAI',
    inputPrice: 10.00,
    outputPrice: 30.00,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 128000,
    capabilities: ['text', 'vision', 'multimodal'],
    category: 'multimodal',
    isLatest: false,
    notes: 'Legacy GPT-4 Turbo model'
  },
  {
    modelId: 'gpt-4',
    modelName: 'GPT-4',
    provider: 'OpenAI',
    inputPrice: 30.00,
    outputPrice: 60.00,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 8192,
    capabilities: ['text'],
    category: 'text',
    isLatest: false,
    notes: 'Legacy GPT-4 base model'
  },
  {
    modelId: 'gpt-3.5-turbo-0125',
    modelName: 'GPT-3.5 Turbo (0125)',
    provider: 'OpenAI',
    inputPrice: 0.50,
    outputPrice: 1.50,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 16385,
    capabilities: ['text'],
    category: 'text',
    isLatest: false,
    notes: 'Legacy GPT-3.5 Turbo model'
  },
  {
    modelId: 'gpt-3.5-turbo',
    modelName: 'GPT-3.5 Turbo',
    provider: 'OpenAI',
    inputPrice: 0.50,
    outputPrice: 1.50,
    unit: PricingUnit.Per1MTokens,
    contextWindow: 16385,
    capabilities: ['text'],
    category: 'text',
    isLatest: false,
    notes: 'Legacy GPT-3.5 Turbo model'
  }
];
