name: Manual Publish to npm

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 1.4.5)'
        required: true
        type: string

jobs:
  manual-publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.AI_GITHUB_TOKEN }}
        ssh-strict: false
    
    - name: Use Node.js
      uses: actions/setup-node@v5
      with:
        node-version: '20'
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
    
    - name: Build package
      run: npm run build
    
    - name: Verify npm token
      run: |
        if [ -n "${{ secrets.NPM_TOKEN }}" ]; then
          echo "NPM_TOKEN is available"
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
          echo "registry=https://registry.npmjs.org/" >> ~/.npmrc
          
          # Test token with a simple API call instead of npm whoami
          echo "Testing npm token..."
          if curl -H "Authorization: Bearer ${{ secrets.NPM_TOKEN }}" \
                  -H "Accept: application/json" \
                  https://registry.npmjs.org/-/whoami 2>/dev/null | grep -q "username"; then
            echo "✅ NPM token is valid"
          else
            echo "❌ NPM token is invalid or has insufficient permissions"
            echo "Please check that your NPM_TOKEN has the following permissions:"
            echo "- Read packages"
            echo "- Publish packages"
            exit 1
          fi
        else
          echo "NPM_TOKEN is not available"
          exit 1
        fi
    
    - name: Update version
      run: |
        npm version ${{ github.event.inputs.version }} --no-git-tag-version
        echo "Updated version to ${{ github.event.inputs.version }}"
    
    - name: Publish to npm
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
        npm publish --access public --registry=https://registry.npmjs.org/
    
    - name: Create git tag
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git remote set-url origin https://x-access-token:${{ secrets.AI_GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        git add package.json
        git commit -m "Bump version to ${{ github.event.inputs.version }}"
        git tag -a "v${{ github.event.inputs.version }}" -m "Release version ${{ github.event.inputs.version }}"
        git push origin HEAD:${{ github.ref }}
        git push origin "v${{ github.event.inputs.version }}" 